# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jun Wang's Blog
author: Gavin
email: netgene@163.com
description: > # this means to ignore newlines until "baseurl:"
  Just make it happen! 
url: https://netgene.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
words: 以梦为马莫负韶华

# Markdown Processors
markdown: kramdown
kramdown:
    input: GFM
    use_coderay: true
    extensions: ["fenced_code_blocks", "footnotes", "smart", hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

plugins:
  - jekyll-paginate
paginate: 20
paginate_path: "/pages:num/"

mathjax: false

excerpt_separator: <!-- more -->

permalink: /:categories/:title.html

social_media:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: netgene
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: netgene
    repo: blog-comments
    oauth:
        client_id: 09b6f38465cdea8d414a
        client_secret: 9dbe7023e2fc6fd146ab23ad012656ae2e0ae458
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: netgene
    repo: blog-comments
    clientID: 09b6f38465cdea8d414a
    clientSecret: 9dbe7023e2fc6fd146ab23ad012656ae2e0ae458
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true